export declare const desktopMenuGroup: string;
export declare const desktopMenuGroupLabel: string;
export declare const desktopMenuGroups: string;
export declare const desktopMenuItem: string;
export declare const desktopMenuItemIcon: string;
export declare const desktopMenuItemLabel: string;
export declare const desktopMenuItemReact: string;
export declare const desktopMenuPopup: string;
export declare const desktopMenuTrigger: string;
